tasks:
  - init: |
      yarn
    command: |
      yarn run dev

vscode:
  extensions:
    - wayou.vscode-todo-highlight
    - k--kato.intellij-idea-keybindings
    - sleistner.vscode-fileutils
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - fabiospampinato.vscode-todo-plus
